version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
